### PR TITLE
Support for Riak 2.0. Ability to use special indices $bucket, $key. Ability to provide max_results and continuation in db.query and get continuation back.

### PR DESCRIPTION
**Pull request by mogadanez**

### CODE REVIEW

**Comment by mogadanez** [comment]
Sorry for delay, test updated and test client  now used.

**Comment by mogadanez** [comment]
ping

**Comment by mogadanez** [comment]
BTW, official node library is in active development
https://github.com/basho/riak-nodejs-client
probably good alternative

**Comment by zowers** [comment]
any eta on when somebody can merge this?

**Comment by Quentin01** [comment]
This PR looks good. So, I merge it now. But I think we must do some refactor later on some things.

**Pull request merged**
